spring:
  application:
    name: NoCode
  # 数据源配置：归属到 spring 节点下，缩进和 application 同级
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/no_code?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 293928
  # springdoc-openapi(knife4j) 配置：同样归属到 spring 节点下
  springdoc:
    group-configs:
      - group: 'default'
        packages-to-scan: com.lzy.nocode.controller

# server 配置：和 spring 同级（注意缩进）
server:
  port: 8080
  servlet:
    context-path: /api

# knife4j 配置：和 spring、server 同级
knife4j:
  enable: true
  setting:
    language: zh_cn

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-190976b3000c46278ad00d7fa19f77af
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-190976b3000c46278ad00d7fa19f77af
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
