spring:
  application:
    name: NoCode
server:
  port: 8080
  servlet:
    context-path: /api
# springdoc-openapi(knife4j)
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.lzy.nocode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

