spring:
  application:
    name: NoCode
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
    # cookie 30 天过期
    cookie:
      max-age: 2592000
  # 数据源配置：归属到 spring 节点下，缩进和 application 同级
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/no_code?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 293928
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600


  # springdoc-openapi(knife4j) 配置：同样归属到 spring 节点下
  springdoc:
    group-configs:
      - group: 'default'
        packages-to-scan: com.lzy.nocode.controller

# server 配置：和 spring 同级（注意缩进）
server:
  port: 8080
  servlet:
    context-path: /api

# knife4j 配置：和 spring、server 同级
knife4j:
  enable: true
  setting:
    language: zh_cn

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-190976b3000c46278ad00d7fa19f77af
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-190976b3000c46278ad00d7fa19f77af
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: your-custom-domain.com
    secretId: your-secret-id
    secretKey: your-secret-key
    region: ap-shanghai
    bucket: your-bucket-name
